spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/usersdb}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:b0KbyH3OD0YO}
    driver-class-name: org.postgresql.Driver
    hikari:
      # Pool configuration for development
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      validation-timeout: 5000
      idle-timeout: 300000
      max-lifetime: 600000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      # Performance optimizations
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 100
        prepStmtCacheSqlLimit: 1024
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

# Undertow configuration for development
server:
  undertow:
    threads:
      io: 4
      worker: 50
    buffer-size: 512
    max-connections: 1000
    max-http-post-size: 1MB
    no-request-timeout: 30000
    request-parse-timeout: 15000
    idle-timeout: 15000

# Logging para desenvolvimento
logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.postgresql: INFO
    io.undertow: WARN

# Swagger/OpenAPI Configuration (apenas em dev)
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  show-actuator: true

app:
  security:
    allow-swagger: true
    public-health-enabled: true
    cors:
      allowed-origins: http://localhost:3000,http://localhost:8080,http://localhost:8081
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: Authorization,Content-Type,X-Requested-With,Accept,Origin
