spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/usersdb_stage}
    username: ${DB_USERNAME:stage_user}
    password: ${DB_PASSWORD:stage_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      # Pool configuration for staging
      maximum-pool-size: 15
      minimum-idle: 3
      connection-timeout: 20000
      validation-timeout: 5000
      idle-timeout: 300000
      max-lifetime: 900000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      # Performance optimizations
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 200
        prepStmtCacheSqlLimit: 1536
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

# Undertow configuration for staging
server:
  undertow:
    threads:
      io: 6
      worker: 100
    buffer-size: 1024
    max-connections: 5000
    max-http-post-size: 2MB
    no-request-timeout: 45000
    request-parse-timeout: 20000
    idle-timeout: 20000

# Logging para staging
logging:
  level:
    root: WARN
    com.example: INFO
    org.springframework.orm.jpa: INFO
    org.postgresql: WARN
    io.undertow: WARN
