spring:
  application:
    name: user-service
  profiles:
    active: dev

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update  # Hibernate gerencia o schema automaticamente
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  # Cache configuration
  cache:
    type: simple
    cache-names:
      - users

# Management and monitoring
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: ""
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: when-authorized
    health-path:
      enabled: false
    info:
      enabled: false
    metrics:
      enabled: false
    prometheus:
      enabled: false
    env:
      enabled: false
    configprops:
      enabled: false

# Server configuration - Undertow
server:
  port: 8080
  servlet:
    context-path: /
  undertow:
    # Thread configuration
    threads:
      io: 8
      worker: 200
    # Buffer configuration
    buffer-size: 1024
    direct-buffers: true
    # Connection configuration
    max-connections: 10000
    max-http-post-size: 2MB
    # Performance optimizations
    eager-filter-init: true
    always-set-keep-alive: true
    no-request-timeout: 60000
    request-parse-timeout: 30000
    idle-timeout: 30000
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Logging configuration
logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:dtU/e4pdvBIee1JM8PEgfeols32HCApOPcar7dKJYGo=}
  expiration: ${JWT_EXPIRATION:3600000}  # 1 hour in milliseconds
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}  # 7 days in milliseconds

# Application Configuration
app:
  password-reset:
    enabled: ${PASSWORD_RESET_ENABLED:true}

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.seccreto.service.auth.controller
  paths-to-exclude: /actuator/**,/health/**

# Application info
info:
  app:
    name: ${spring.application.name}
    description: User Management Service
    version: 1.0.0
    encoding: UTF-8
    java:
      version: ${java.version}
